---
Name: goldfinch-socialmedia
After:
  - '#goldfinch-basement'
---

Goldfinch\SocialMedia\Models\SocialPost:
  post_tag_link: true
  post_at_link: true
  post_no_break: true
  post_links: true

SilverStripe\Control\Director:
  rules:
    'api/meta': App\Controllers\ApiMetaController

Goldfinch\SocialMedia\Admin\SocialMediaAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension
