---
Name: goldfinch-socialkit
After:
  - '#goldfinch-basement'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\SocialKit\Extensions\SiteConfigExtension

SilverStripe\Control\Director:
  rules:
    'api/meta': App\Controllers\ApiMetaController
